adding few more events
KaranGauswami/freeswitch-esl pull request #3
Opened 2023-08-22 20:02 UTC by srikarm99

2023-09-02 05:37 UTC, KaranGauswami requested changes
Thanks for the PR, Everything else looks good.

2023-09-02 05:37 UTC, KaranGauswami commented on Cargo.toml
> +tokio = { version = "1", features = ["full"] }
I think we dont need this full features here, everything else is fine. Thanks.

2023-09-02 05:37 UTC, KaranGauswami commented on Cargo.toml
> +tokio = { version = "1", features = ["full"] }
Same as above comment.

2023-09-04 06:33 UTC, srikarm99 commented
Hi, I reverted the features, will also add some test cases and examples for the written functions

2023-09-05 14:55 UTC, KaranGauswami approved these changes

2023-09-05 14:56 UTC, merged

2023-09-05 14:56 UTC, KaranGauswami commented
Thanks, Merged now.